### ISSUE TITLE
code is breaking after new update

### ISSUE THREAD

**Issue by a-lakh** [SongweiGe/rich-text-to-image#11]
`Traceback (most recent call last):
  File "sample.py", line 146, in <module>
    main(args, param)
  File "sample.py", line 66, in main
    plain_img = model.produce_attn_maps([base_text_prompt], [negative_text],
  File "/Users/stark/work/rich-text-to-image/models/region_diffusion.py", line 207, in produce_attn_maps
    noise_pred = self.unet(
  File "/Users/stark/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/stark/work/rich-text-to-image/models/unet_2d_condition.py", line 908, in forward
    sample, res_samples = downsample_block(
  File "/Users/stark/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/stark/work/rich-text-to-image/models/unet_2d_blocks.py", line 999, in forward
    hidden_states = attn(
  File "/Users/stark/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/stark/work/rich-text-to-image/models/transformer_2d.py", line 291, in forward
    hidden_states = block(
  File "/Users/stark/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/stark/work/rich-text-to-image/models/attention.py", line 155, in forward
    attn_output, _ = self.attn1(
  File "/Users/stark/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/Users/stark/work/rich-text-to-image/models/attention_processor.py", line 330, in forward
    return self.processor(
TypeError: __call__() got an unexpected keyword argument 'real_attn_probs'`

**Comment by SongweiGe** [comment]
Are you trying to use a different Attention Processor other than the [default one](https://github.com/SongweiGe/rich-text-to-image/blob/65e54f536989c5ad1c9a5b56f2916cc438246990/models/attention_processor.py#L470)? Currently, the implementation of token reweighting only supports the normal attention computation.

Also, may I know the command you used to run?

**Comment by huangswmt** [comment]
i got the same error,when I first git this project.

**Comment by songweige** [comment]
Thank you for trying it out! Could you please provide more information so that I can reproduce the error? For example, could you please provide the results of `conda list`?

**Comment by wwj1013** [comment]
My environment is torch=2.0.1+cu118, and the rest of the installation packages are the same as the requirements in your configuration file. Then, the relevant model SDXL of the hugging face is downloaded locally (I'm not sure if it will make a difference), and the command to run is `python gradio_app.py`

**Comment by songweige** [comment]
There was an issue when using PyTorch with version >= `2.0.0`. I have made an update to fix it. Please let me know if the issue is still there! Thanks!
