### ISSUE TITLE
RuntimeError: main thread is not in main loop

### ISSUE THREAD

**Issue by pcxdi** [SongweiGe/rich-text-to-image#17]
Exception ignored in: <function Variable.__del__ at 0x000001CBE63F3B80>
Traceback (most recent call last):
  File "D:\anaconda\envs\pytorch\rich-text-to-image-main\lib\tkinter\__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x000001CBE63F3B80>
Traceback (most recent call last):
  File "D:\anaconda\envs\pytorch\rich-text-to-image-main\lib\tkinter\__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
How do I solve this threading problem

**Comment by songweige** [comment]
Does this also happen when you try to launch the gradio demo? Could you paste the entire error log so that I could know where the code causes the error?
