### ISSUE TITLE
An error message for the Gradio library indicating that a validation error occurred while processing the event. Specifically, the error is caused by the missing "event_id" field

### ISSUE THREAD

**Issue by pcxdi** [SongweiGe/rich-text-to-image#18]
Traceback (most recent call last):
  File "D:\anaconda\envs\pytorch\rich-text-to-image-main\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "D:\anaconda\envs\pytorch\rich-text-to-image-main\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "D:\anaconda\envs\pytorch\rich-text-to-image-main\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "D:\anaconda\envs\pytorch\rich-text-to-image-main\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 10, 'data': ...on_hash': '3yq8r3v8to9'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing

**Comment by songweige** [comment]
Interesting. May I know what is your version of gradio?
