### ISSUE TITLE
Without manually creating results folder, an error occurs.

### ISSUE THREAD

**Issue by JPW0080** [SongweiGe/rich-text-to-image#3]
Win 11 and Win 11+WSL2/Ubuntu 20.04

If results folder has not been created in the rich-text-to-image folder before launching gradio_app.py
An error occurs when attempting to Generate:

(rich-text) C:\various-apps\rich-text-to-image>python gradio_app.py
[INFO] loading stable diffusion...
[INFO] loaded stable diffusion!
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
time lapses to get attention maps: 9.0908
C:\various-apps\rich-text-to-image\utils\attention_utils.py:42: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  plt.figure()
C:\various-apps\rich-text-to-image\utils\attention_utils.py:45: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  fig, axs = plt.subplots(
Traceback (most recent call last):
  File "C:\Anaconda3\envs\rich-text\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Anaconda3\envs\rich-text\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "C:\Anaconda3\envs\rich-text\lib\site-packages\gradio\blocks.py", line 915, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Anaconda3\envs\rich-text\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Anaconda3\envs\rich-text\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Anaconda3\envs\rich-text\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "gradio_app.py", line 76, in generate
    color_obj_masks, token_maps = get_token_maps(
  File "C:\various-apps\rich-text-to-image\utils\attention_utils.py", line 205, in get_token_maps
    token_maps_vis = plot_attention_maps([attention_maps_averaged, attention_maps_averaged_normalized],
  File "C:\various-apps\rich-text-to-image\utils\attention_utils.py", line 88, in plot_attention_maps
    plt.savefig(os.path.join(
  File "C:\Anaconda3\envs\rich-text\lib\site-packages\matplotlib\pyplot.py", line 1023, in savefig
    res = fig.savefig(*args, **kwargs)
  File "C:\Anaconda3\envs\rich-text\lib\site-packages\matplotlib\figure.py", line 3343, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\Anaconda3\envs\rich-text\lib\site-packages\matplotlib\backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "C:\Anaconda3\envs\rich-text\lib\site-packages\matplotlib\backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "C:\Anaconda3\envs\rich-text\lib\site-packages\matplotlib\backends\backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "C:\Anaconda3\envs\rich-text\lib\site-packages\matplotlib\backends\backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "C:\Anaconda3\envs\rich-text\lib\site-packages\matplotlib\image.py", line 1689, in imsave
    image.save(fname, **pil_kwargs)
  File "C:\Anaconda3\envs\rich-text\lib\site-packages\PIL\Image.py", line 2428, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'results/token_maps_seed62476_presoftmax.png'

**Comment by SongweiGe** [comment]
Thank you for your interest and for pointing that out. I have made a [quick fix](https://github.com/SongweiGe/rich-text-to-image/commit/c5c4a30295ed7042d27da8efc0412bd2dfe5c410).
